const GAMEPAD_X = 0;
const GAMEPAD_SQUARE = 2;
const GAMEPAD_TRIANGLE = 2;
const GAMEPAD_CIRCLE = 3;
const GAMEPAD_LEFT_TRIGGER_1 = 4;
const GAMEPAD_RIGHT_TRIGGER_1 = 5;
const GAMEPAD_LEFT_TRIGGER_2 = 6;
const GAMEPAD_RIGHT_TRIGGER_2 = 7;
const GAMEPAD_SELECT = 8;
const GAMEPAD_START = 9;
const GAMEPAD_LEFT_STICK = 10;
const GAMEPAD_RIGHT_STICK = 11;
const GAMEPAD_ARROW_UP = 12;
const GAMEPAD_ARROW_DOWN = 13;
const GAMEPAD_ARROW_LEFT = 14;
const GAMEPAD_ARROW_RIGHT = 15;

export {
    // GAMEPAD KEY CODES
    GAMEPAD_X,
    GAMEPAD_SQUARE,
    GAMEPAD_TRIANGLE,
    GAMEPAD_CIRCLE,
    GAMEPAD_LEFT_TRIGGER_1,
    GAMEPAD_RIGHT_TRIGGER_1,
    GAMEPAD_LEFT_TRIGGER_2,
    GAMEPAD_RIGHT_TRIGGER_2,
    GAMEPAD_SELECT,
    GAMEPAD_START,
    GAMEPAD_LEFT_STICK,
    GAMEPAD_RIGHT_STICK,
    GAMEPAD_ARROW_UP,
    GAMEPAD_ARROW_DOWN,
    GAMEPAD_ARROW_LEFT,
    GAMEPAD_ARROW_RIGHT
}